CI - convert pylint to soft check

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -16,4 +16,9 @@ jobs:
           python -m pip install --upgrade pip
           pip install pylint
       - name: Pylint check
-        run: dev_tools/pylint
+        # TODO: #210 - convert to hard check when lint is picked up
+        run: |
+          dev_tools/pylint || (
+            echo "pylint check failed.  The error is temporarily ignored."
+            echo "See https://github.com/quantumlib/unitary/issues/210"
+          )
